services:
  api:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      QDRANT_PATH: /app/qdrant_db
      OLLAMA_HOST: http://host.docker.internal:11434
    volumes:
      - ./app/qdrant_db:/app/qdrant_db    # ← mount local qdrant folder
    restart: on-failure
