services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./app/qdrant_db:/qdrant/storage

  app:
    build: .
    container_name: rag-streamlit
    ports:
      - "8501:8501"        # ← Streamlit port
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant
    restart: on-failure